version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=carrental
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    command: ["./wait-for-db.sh", "npm", "start"]

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: carrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
